import "oaidl.idl";
import "ocidl.idl";

typedef enum {CONTROLEVENT_C, CONTROLEVENT_BREAK} ControlEvent;

[
	object,
	uuid(C9ABBC7D-280C-4A8C-B6FE-EC95FD50E44A),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IExec : IDispatch{
	[] HRESULT Ping();
	[] HRESULT PrepareWindowStation([out] BYTE* success);
	[] HRESULT IsWindowStationPrepared([out] BYTE* prepared);
	[] HRESULT StartProcess([in] BSTR commandLine, [in] BSTR workingDir, [in] BSTR *environment, [out] BYTE* success, [out] LONGLONG* error);
	[] HRESULT GetTerminationStatus([out] BYTE* hasTerminated, [out] LONGLONG* exitCode);
	[] HRESULT ReadStdout([out] BSTR* data, [out] long *dataLength);
	[] HRESULT ReadStderr([out] BSTR* data, [out] long *dataLength);
	[] HRESULT WriteStdin([in] BSTR* data, [in] long dataLength);
	[] HRESULT SendControl(ControlEvent evt);
};



[
	object,
	uuid(D9E61F1B-4A48-4A08-8C71-150DFB6C4748),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPrepareWindowStationComm : IDispatch{
	[] HRESULT Attach([in] BSTR preparationId);
	[] HRESULT GetData([out] BSTR* desktopName, [out] BSTR* clientSidString);
	[] HRESULT IsActive([out] BYTE* active);
	[] HRESULT PreparationCompleted();
	[] HRESULT GetConsoleEventOrder([out] BYTE *hasOrder, [out] DWORD *processId, [out] ControlEvent *evt);
};


[
	uuid(B6EBFBF7-CD9F-4172-92F8-EE7D12CFC703),
	version(1.0),
]
library ConsoleServerLib
{
	importlib("stdole2.tlb");

	[
		uuid(696511A9-45A2-4CFB-834F-CD134A7FFF5A)		
	]
	coclass Exec
	{
		[default] interface IExec;
	};

	[
		uuid(158AA083-89FF-48CD-9123-299FDB200B28)		
	]
	coclass PrepareWindowStationComm
	{
		[default] interface IPrepareWindowStationComm;
	};
};

